# Generated by Django 5.0.3 on 2026-05-11 10:54

import os

from django.db import migrations


def add_module03_and_exam(apps, schema_editor):
    """Add Module 03 lesson and picoshell exam"""
    # Skip data population during tests
    import sys
    if 'pytest' in sys.modules or 'test' in sys.argv:
        return

    Lesson = apps.get_model('lms', 'Lesson')
    Exam = apps.get_model('lms', 'Exam')

    # Read lesson content
    lessons_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'lessons')
    lesson_file = os.path.join(lessons_dir, 'module-03-picoshell.md')

    with open(lesson_file, 'r') as f:
        content = f.read()

    # Create Module 03 lesson
    Lesson.objects.create(
        lesson_id='module-03',
        title='Understanding Shells',
        subtitle='The Foundation of AI Agent Execution',
        content=content,
        module_number=3,
        order_index=3
    )

    # Create picoshell exam
    Exam.objects.create(
        exam_id='picoshell',
        title='Picoshell Implementation',
        instructions='''# Picoshell Exam

Implement a simplified shell that executes commands and handles pipes.

## Requirements

Your program must:
1. Take command-line arguments representing a command pipeline
2. Execute commands using fork() and execvp()
3. Handle the pipe operator `|`
4. Support multiple pipes

## Examples

```bash
./picoshell echo hello
# Output: hello

./picoshell echo hello | cat
# Output: hello

./picoshell echo "hello world" | cat | cat
# Output: hello world
```

## Grading

- All tests must pass (100% required)
- Exact output match (whitespace matters)
- 5-second timeout per test
- Implement in C, Python, or TypeScript

## Submission

Create your file in `~/exam/` with the correct name:
- C: `picoshell.c`
- Python: `picoshell.py`
- TypeScript: `picoshell.ts`

Submit with: `lms exam submit picoshell --lang <language>`
''',
        time_limit_minutes=60
    )


def reverse_migration(apps, schema_editor):
    """Remove Module 03 lesson and picoshell exam"""
    Lesson = apps.get_model('lms', 'Lesson')
    Exam = apps.get_model('lms', 'Exam')

    Lesson.objects.filter(lesson_id='module-03').delete()
    Exam.objects.filter(exam_id='picoshell').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_exam_examsession_examsubmission_and_more'),
    ]

    operations = [
        migrations.RunPython(add_module03_and_exam, reverse_migration),
    ]
